# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maths.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 900))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 124);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LinearRegressionLabel = QtWidgets.QLabel(self.centralwidget)
        self.LinearRegressionLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.LinearRegressionLabel.setText("")
        self.LinearRegressionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LinearRegressionLabel.setObjectName("LinearRegressionLabel")
        self.verticalLayout_2.addWidget(self.LinearRegressionLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LinearRegressionOut1Label = QtWidgets.QLabel(self.centralwidget)
        self.LinearRegressionOut1Label.setMinimumSize(QtCore.QSize(0, 50))
        self.LinearRegressionOut1Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.LinearRegressionOut1Label.setText("")
        self.LinearRegressionOut1Label.setScaledContents(True)
        self.LinearRegressionOut1Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LinearRegressionOut1Label.setObjectName("LinearRegressionOut1Label")
        self.horizontalLayout_4.addWidget(self.LinearRegressionOut1Label)
        self.LinearRegressionOut2Label = QtWidgets.QLabel(self.centralwidget)
        self.LinearRegressionOut2Label.setMinimumSize(QtCore.QSize(0, 50))
        self.LinearRegressionOut2Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.LinearRegressionOut2Label.setText("")
        self.LinearRegressionOut2Label.setScaledContents(True)
        self.LinearRegressionOut2Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LinearRegressionOut2Label.setObjectName("LinearRegressionOut2Label")
        self.horizontalLayout_4.addWidget(self.LinearRegressionOut2Label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.LinearRegressionButton = QtWidgets.QPushButton(self.centralwidget)
        self.LinearRegressionButton.setStyleSheet("border-color: rgb(0, 0, 81);\n"
"font: 75 8pt \"Bell MT\";\n"
"background-color: rgb(134, 203, 255);")
        self.LinearRegressionButton.setObjectName("LinearRegressionButton")
        self.verticalLayout_2.addWidget(self.LinearRegressionButton)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ExponentialLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExponentialLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.ExponentialLabel.setText("")
        self.ExponentialLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ExponentialLabel.setObjectName("ExponentialLabel")
        self.verticalLayout_3.addWidget(self.ExponentialLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ExponentialOut1Label = QtWidgets.QLabel(self.centralwidget)
        self.ExponentialOut1Label.setMinimumSize(QtCore.QSize(0, 50))
        self.ExponentialOut1Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.ExponentialOut1Label.setText("")
        self.ExponentialOut1Label.setScaledContents(True)
        self.ExponentialOut1Label.setObjectName("ExponentialOut1Label")
        self.horizontalLayout_5.addWidget(self.ExponentialOut1Label)
        self.ExponentialOut2Label = QtWidgets.QLabel(self.centralwidget)
        self.ExponentialOut2Label.setMinimumSize(QtCore.QSize(0, 50))
        self.ExponentialOut2Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.ExponentialOut2Label.setText("")
        self.ExponentialOut2Label.setScaledContents(True)
        self.ExponentialOut2Label.setObjectName("ExponentialOut2Label")
        self.horizontalLayout_5.addWidget(self.ExponentialOut2Label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.ExponentialButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExponentialButton.setStyleSheet("border-color: rgb(0, 0, 81);\n"
"font: 75 8pt \"Bell MT\";\n"
"background-color: rgb(134, 203, 255);")
        self.ExponentialButton.setObjectName("ExponentialButton")
        self.verticalLayout_3.addWidget(self.ExponentialButton)
        self.verticalLayout_3.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.NewtonRaphsonLabel = QtWidgets.QLabel(self.centralwidget)
        self.NewtonRaphsonLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.NewtonRaphsonLabel.setText("")
        self.NewtonRaphsonLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NewtonRaphsonLabel.setObjectName("NewtonRaphsonLabel")
        self.verticalLayout_6.addWidget(self.NewtonRaphsonLabel)
        self.NewtonRaphsonout1Label = QtWidgets.QLabel(self.centralwidget)
        self.NewtonRaphsonout1Label.setMinimumSize(QtCore.QSize(0, 50))
        self.NewtonRaphsonout1Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.NewtonRaphsonout1Label.setText("")
        self.NewtonRaphsonout1Label.setObjectName("NewtonRaphsonout1Label")
        self.verticalLayout_6.addWidget(self.NewtonRaphsonout1Label)
        self.NewtonRaphsonButton = QtWidgets.QPushButton(self.centralwidget)
        self.NewtonRaphsonButton.setStyleSheet("border-color: rgb(0, 0, 81);\n"
"font: 75 8pt \"Bell MT\";\n"
"background-color: rgb(134, 203, 255);")
        self.NewtonRaphsonButton.setObjectName("NewtonRaphsonButton")
        self.verticalLayout_6.addWidget(self.NewtonRaphsonButton)
        self.verticalLayout_6.setStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TrapezoidalLabel = QtWidgets.QLabel(self.centralwidget)
        self.TrapezoidalLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.TrapezoidalLabel.setText("")
        self.TrapezoidalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TrapezoidalLabel.setObjectName("TrapezoidalLabel")
        self.verticalLayout_4.addWidget(self.TrapezoidalLabel)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LowLimit = QtWidgets.QSpinBox(self.centralwidget)
        self.LowLimit.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.LowLimit.setObjectName("LowLimit")
        self.horizontalLayout_7.addWidget(self.LowLimit)
        self.UpLimit = QtWidgets.QSpinBox(self.centralwidget)
        self.UpLimit.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.UpLimit.setObjectName("UpLimit")
        self.horizontalLayout_7.addWidget(self.UpLimit)
        self.SubIntervalNum = QtWidgets.QSpinBox(self.centralwidget)
        self.SubIntervalNum.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.SubIntervalNum.setObjectName("SubIntervalNum")
        self.horizontalLayout_7.addWidget(self.SubIntervalNum)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.TrapezoidalOutLabel = QtWidgets.QLabel(self.centralwidget)
        self.TrapezoidalOutLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.TrapezoidalOutLabel.setObjectName("TrapezoidalOutLabel")
        self.horizontalLayout_15.addWidget(self.TrapezoidalOutLabel)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_15.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.TrapezoidalButton = QtWidgets.QPushButton(self.centralwidget)
        self.TrapezoidalButton.setStyleSheet("border-color: rgb(0, 0, 81);\n"
"font: 75 8pt \"Bell MT\";\n"
"background-color: rgb(134, 203, 255);")
        self.TrapezoidalButton.setObjectName("TrapezoidalButton")
        self.verticalLayout_4.addWidget(self.TrapezoidalButton)
        self.verticalLayout_4.setStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LinearRegressionButton.setText(_translate("MainWindow", "Linear Regression"))
        self.ExponentialButton.setText(_translate("MainWindow", "Exponential Model"))
        self.NewtonRaphsonButton.setText(_translate("MainWindow", "Newton-Raphson Method"))
        self.label_3.setText(_translate("MainWindow", "Lower limit:"))
        self.label_2.setText(_translate("MainWindow", "Upper limit:"))
        self.label.setText(_translate("MainWindow", "Sub intervals number:"))
        self.TrapezoidalOutLabel.setText(_translate("MainWindow", "Integration Result ="))
        self.TrapezoidalButton.setText(_translate("MainWindow", "Trapezoidal Method"))

