# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maths.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(903, 400))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 124);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LinearRegressionLabel = QtWidgets.QLabel(self.centralwidget)
        self.LinearRegressionLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.LinearRegressionLabel.setText("")
        self.LinearRegressionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LinearRegressionLabel.setObjectName("LinearRegressionLabel")
        self.verticalLayout_2.addWidget(self.LinearRegressionLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LinearRegressionOut1Label = QtWidgets.QLabel(self.centralwidget)
        self.LinearRegressionOut1Label.setMinimumSize(QtCore.QSize(0, 50))
        self.LinearRegressionOut1Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.LinearRegressionOut1Label.setText("")
        self.LinearRegressionOut1Label.setScaledContents(True)
        self.LinearRegressionOut1Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LinearRegressionOut1Label.setObjectName("LinearRegressionOut1Label")
        self.horizontalLayout_4.addWidget(self.LinearRegressionOut1Label)
        self.LinearRegressionOut2Label = QtWidgets.QLabel(self.centralwidget)
        self.LinearRegressionOut2Label.setMinimumSize(QtCore.QSize(0, 50))
        self.LinearRegressionOut2Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.LinearRegressionOut2Label.setText("")
        self.LinearRegressionOut2Label.setScaledContents(True)
        self.LinearRegressionOut2Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LinearRegressionOut2Label.setObjectName("LinearRegressionOut2Label")
        self.horizontalLayout_4.addWidget(self.LinearRegressionOut2Label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.LinearRegressionButton = QtWidgets.QPushButton(self.centralwidget)
        self.LinearRegressionButton.setStyleSheet("border-color: rgb(0, 0, 81);\n"
"font: 75 8pt \"Bell MT\";\n"
"background-color: rgb(134, 203, 255);")
        self.LinearRegressionButton.setObjectName("LinearRegressionButton")
        self.verticalLayout_2.addWidget(self.LinearRegressionButton)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.powerLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.powerLabel.setText("")
        self.powerLabel.setObjectName("powerLabel")
        self.verticalLayout_5.addWidget(self.powerLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.powerOutLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerOutLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.powerOutLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.powerOutLabel.setText("")
        self.powerOutLabel.setObjectName("powerOutLabel")
        self.horizontalLayout.addWidget(self.powerOutLabel)
        self.powerOut2Label = QtWidgets.QLabel(self.centralwidget)
        self.powerOut2Label.setMinimumSize(QtCore.QSize(0, 50))
        self.powerOut2Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.powerOut2Label.setText("")
        self.powerOut2Label.setObjectName("powerOut2Label")
        self.horizontalLayout.addWidget(self.powerOut2Label)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.powerButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerButton.setStyleSheet("border-color: rgb(0, 0, 81);\n"
"font: 75 8pt \"Bell MT\";\n"
"background-color: rgb(134, 203, 255);background-color: rgb(134, 203, 255);")
        self.powerButton.setObjectName("powerButton")
        self.verticalLayout_5.addWidget(self.powerButton)
        self.verticalLayout_5.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ExponentialLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExponentialLabel.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.ExponentialLabel.setText("")
        self.ExponentialLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ExponentialLabel.setObjectName("ExponentialLabel")
        self.verticalLayout_3.addWidget(self.ExponentialLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ExponentialOut1Label = QtWidgets.QLabel(self.centralwidget)
        self.ExponentialOut1Label.setMinimumSize(QtCore.QSize(0, 50))
        self.ExponentialOut1Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.ExponentialOut1Label.setText("")
        self.ExponentialOut1Label.setScaledContents(True)
        self.ExponentialOut1Label.setObjectName("ExponentialOut1Label")
        self.horizontalLayout_5.addWidget(self.ExponentialOut1Label)
        self.ExponentialOut2Label = QtWidgets.QLabel(self.centralwidget)
        self.ExponentialOut2Label.setStyleSheet("background-color: rgb(134, 203, 255);")
        self.ExponentialOut2Label.setText("")
        self.ExponentialOut2Label.setObjectName("ExponentialOut2Label")
        self.horizontalLayout_5.addWidget(self.ExponentialOut2Label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.ExponentialButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExponentialButton.setStyleSheet("border-color: rgb(0, 0, 81);\n"
"font: 75 8pt \"Bell MT\";\n"
"background-color: rgb(134, 203, 255);")
        self.ExponentialButton.setObjectName("ExponentialButton")
        self.verticalLayout_3.addWidget(self.ExponentialButton)
        self.verticalLayout_3.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LinearRegressionButton.setText(_translate("MainWindow", "Linear Regression"))
        self.powerButton.setText(_translate("MainWindow", "Power model"))
        self.ExponentialButton.setText(_translate("MainWindow", "Exponential Model"))

